### PR TITLE
The decent web is best hope for the internet's future

### PR DESCRIPTION
**Pull request by lloydwatkin**

### CODE REVIEW

**Comment by bastianallgeier** [comment]
I confess that it's a bit ironic to put it on Github. And yet I think it's the best way to make it available for everyone at the moment. Maybe I should add. The decent web is work in progress :)

**Comment by lloydwatkin** [comment]
Joking aside, that's a very good one!

**Comment by lloydwatkin** [comment]
Thanks for organising decentralize camp too, it was awesome. If I can be of any help for next year (because I insist you do it again ;-) ) please let me know.

**Comment by bastianallgeier** [comment]
Haha, thanks for the offer!! I'd love to do it again and it would be awesome to have you on board organizing it.

**Pull request merged**
